### ISSUE TITLE
Contribute to Documentation

### ISSUE THREAD

**Issue by ghostinhershell** [getgrav/grav-learn#355] opened 2016-12-15 13:44 UTC
Hi guys!

I'm @ghostinhershell. I often contact the Grav team via Github whenever I have support questions about Grav. Grav is a software I use almost every day and I would love to contribute to Grav's documentation. If you can suggest any topics that can be improved or added, I'll jump right in and get started.

Thanks!

**Comment by rhukster** [comment] 2016-12-15 16:37
Here's a great place to start: https://github.com/getgrav/grav-learn/issues/356

if you an help with any of these, it would really be appreciated!

**Comment by RyanMPierson** [comment] 2016-12-15 22:18
If you have any questions or concerns just let me or anyone else on the Grav team know in Gitter. I try to answer pings as soon as I get them. You can also comment on this issue or ask away in the pull request(s).

Don't be too worried about being absolutely perfect out of the gate with them. We'll give them a once-over for grammar, spelling, syntax, and consistency after I see the pull request.

Thank you so very much in advance for any help you can lend.

**Comment by ghostinhershell** [comment] 2016-12-16 07:12
Thanks guys :) I'm really excited about being able to contribute.

**Comment by RyanMPierson** [comment] 2017-11-04 15:22
Closing this as it is not a currently outstanding issue with documentation in need of resolving.

**Closed as completed by RyanMPierson** 2017-11-04 15:22 UTC

**Comment by nguiraneramarama-cell** [comment] 2026-01-16 01:46
@faire Amy

**Comment by nguiraneramarama-cell** [comment] 2026-01-16 01:47
****Duplicate of #1139
